# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Asus\Desktop\app_test\Ui\Login\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_username = QtWidgets.QLineEdit(Form)
        self.txt_username.setGeometry(QtCore.QRect(170, 90, 113, 22))
        self.txt_username.setObjectName("txt_username")
        self.txt_password = QtWidgets.QLineEdit(Form)
        self.txt_password.setGeometry(QtCore.QRect(170, 120, 113, 22))
        self.txt_password.setObjectName("txt_password")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_signIn = QtWidgets.QPushButton(Form)
        self.btn_signIn.setGeometry(QtCore.QRect(180, 160, 93, 28))
        self.btn_signIn.setObjectName("btn_signIn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Username :"))
        self.label_2.setText(_translate("Form", "Password :"))
        self.btn_signIn.setText(_translate("Form", "Sign In"))
